config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bikes do
    resources :bookings, only: [:new, :create ] do
      resources :reviews
    end
  end
  get 'bikes/city', to: 'bikes#city_show'
  resources :bookings, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :bookings
  has_many :reviews, through: :bookings, dependent: :destroy
  belongs_to :user
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews
  belongs_to :user
  belongs_to :bike

  validates :start_day, presence: true
  validates :finish_day, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bikes
  has_many :bookings
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  # The callback which stores the current location must be added before you authenticate the user 
  # as `authenticate_user!` (or whatever your resource is) will halt the filter chain and redirect 
  # before the location can be stored.
  before_action :authenticate_user!

  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?
  
  
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
  
  private
  
 
  
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an 
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end
  
    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[show edit update destroy]
  def index
    # Query db -> Get all bikes given location  long/lat

    if params[:bike] && params[:bike][:address].present?
      @address = params[:bike][:address]
      @bikes = Bike.near(@address, 500)
    else
      @address = ''
      @bikes = Bike.all
    end
    @bikes = @bikes.where(category: params[:category]) if params[:category]

    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
        image_url: helpers.asset_url('https://source.unsplash.com/random')
        # add interpolation of bike img here
      }
    end
  end

  #
  # Renter
  #
  def show

    # Query db -> Get bike by ID

  end

  #
  # Biker owner
  #

  def new
    @bike = Bike.new
    # authorize if owner -> yes. else no
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to @bike
    else
      render :new
    end
  end

  def edit
    # authorize if owner -> yes. else no
  end

  def update
    if @bike.update(bike_params)
      redirect_to @bike, notice: 'Bike was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # authorize if owner -> yes. else no
    @bike.destroy
    redirect_to bikes_path
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
    
  end

  # Only allow a list of trusted parameters through.
  def bike_params
    params.require(:bike).permit(:name, :description, :price, :longtitude, :latitude, :category, :photo)
  end
  # Use callbacks to share common setup or constraints between actions.
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ destroy ]
  before_action :set_bike, only: %i[ new create ]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  
  def set_bike
    @bike = Bike.find(params[:bike_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:bike_id, :start_day, :finish_day)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :abc, only: [:index]
  def home
  end

  def index
  end

  def create
    # receive city from page.html form 
    # redirect bike: index.html with city value
  end 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :destroy]
  before_action :set_booking, only: [:new, :create]

  def index
    @reviews = Review.all
  end

  def show
  end


  def new
     @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to bike_path(@booking.bike)
    else
      render "new"
    end
  end

  def destroy
    @review.destroy
    redirect_to bike_bookings_path(@review.booking.bike)
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_bike.html.erb
 <div class="w-full flex mb-4 p-2 rounded-2xl hover:bg-gray-100">
  <div class="overflow-hidden rounded-xl flex-shrink-0 h-36 w-36 border-2 border-white shadow">
    <%= cl_image_tag(bike.photo.key, width: 300, height: 300, crop: :fill) if bike.photo.attached? %>
  </div>
  <div class="p-2 pl-4 flex flex-col justify-between flex-grow-1">
    <div class="flex justify-between">
      <div>
        <h3 class="text-xs px-2 py-1 bg-red-200 text-red-600 inline rounded-md"><%= bike.category %></h3>
        <h2 class="text-xl mt-1"><%= bike.name %></h2>
      </div>
      <div>
        <h4 class="text-lg font-semibold">$<%= bike.price %> <span class="text-gray-400 text-sm">/day</span></h4>
      </div>
    </div>
    <div class="flex justify-end">
      <%= link_to 'See more', bike_path(bike), class:'py-2 px-4 no-underline bg-yellow-200 text-yellow-900 rounded-md' %>
    </div>
  </div>
 </div>

app/views/bikes/_form.html.erb
<%= simple_form_for @bike do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :category %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit %>

<% end %>

app/views/bikes/_info_window.html.erb
<h4><%= bike.name %></h4>
<p><%= bike.address %></p>

app/views/bikes/index.html.erb
<div class="flex bg-#f4f4f4 w-screen top-0" style="height: calc(100vh - 70px)">

    <div class="overflow-scroll h-full w-2/3 p-10">
      <% @bikes.each do |bike| %>
        <%= render 'bike', bike: bike %>
      <% end %>
    </div>

    <div class="w-1/3 h-full"
      id="map"
      style="height: 100%; position: sticky;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

</div>

app/views/bikes/new.html.erb
<div class="p-2 max-w-xl mx-auto">
  <%= render 'form' %>
</div>

app/views/bookings/_form.html.erb
<div class="container py-5">

  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <h2 class="mb-2">Pick a date <h2>
      <div class="bg-white rounded">
        <%= simple_form_for ([@bike, @booking]) do |f| %>
          <%= f.input :start_day, input_html: { id: "flatpickr" }, label_html:{class: "text-sm text-yellow-500"}, as: :string, required:false%>
          <%= f.input :finish_day, input_html: { id: "flatpickr" }, label_html:{class: "text-sm text-yellow-500"}, as: :string, required:false%>
          <%= f.submit class: 'w-full bg-yellow-300 border border-transparent rounded-md py-2 px-8 flex items-center justify-center text-base font-medium text-yellow-700 hover:text-yellow-800 hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-yellow-500' %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h1> All Bookings </h1>

<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Bike name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Start day
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Finish day
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Role
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Note
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @bookings.each do |booking| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">
                
                    <div class="text-sm font-medium text-gray-900">
                      <%= booking.bike.name %>
                    </div>
                      
                   
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    <%= booking.start_day.strftime("%d-%m-%Y")%>
                  </div>
                  
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    <%= booking.finish_day.strftime("%d-%m-%Y")%>
                  </div>
                </td>
                
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    <%= link_to 'Delete', booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to remove your booking?"} %>
                  </div>
                </td>

                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    <%= link_to 'Add a review', new_bike_booking_review_path(booking.bike, booking)  %>
                  </div>
                </td>
              </tr>
            <% end  %>
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="text-center m-4"><%= link_to 'Back', bikes_path %></div>

app/views/bookings/new.html.erb
<div class="container">


  <%= render 'form', bike: @bike, booking: @booking %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeWheelBikes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  <footer>
    <%= render 'shared/footer' %>
  </footer>
  </body>



</html>

app/views/pages/home.html.erb
<%# <div class="container">
<%# <h1>All Categories</h1> %>
  <%# <div class="flex">
    <div class="co-12 colsm-6 col-md-4">
      <div class="card-category" data-aos="zoom-in">
        <h2><%= link_to 'City', bikes_path(category: 'City', bike: { address: @address }) %></h2>
      <%# </div>
    </div> %>

    <%# <div class="co-12 colsm-6 col-md-4">
      <div class="card-category" data-aos="zoom-in">
        <h2><%= link_to 'MTB', bikes_path(category: 'MTB', bike: { address: @address }) %></h2>
      <%# </div>
    </div> %>

    <%# <div class="co-12 colsm-6 col-md-4">
      <div class="card-category" data-aos="zoom-in">
      <h2><%= link_to 'Race', bikes_path(category: 'Race', bike: { address: @address })%></h2>
      <%# </div> %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>

<%#
# action -> ???
# method -> GET
 %>

<%# <section class="text-gray-400 bg-gray-900 body-font"> %>
<%# container %>

  <div class="d-flex justify-content-center mt-4">
    <div class="container-text ml-4 pl-4 d-flex flex-column position-relative justify-content-center">
      <div class="bg-white p-4 rounded shadow position-absolute width">
        <h1>Find a bike you want to ride</h1>
        <p>Discover the perfect bike for your next trip.</p>
        <div class="container d-flex flex-column rounded z-20">
          <form action="<%= bikes_path %>" method="get">
            <label for="address">Location</label>
            <input type="text" id='address' name='address' class='border-2 rounded-md'>

            <div class="card-category" data-aos="zoom-in">
              <%# <p>btn</p> %>
            </div>
           <input type="submit" class='btn btn-info shadow rounded-md mt-2 px-10 w-full text-yellow-700' value="Submit">
          </form>
        </div>
      </div>
    </div>

    <div class="container-img rounded pl-16">
        <img class="object-cover object-center ml-8 img-fluid" alt="hero" src="https://images.unsplash.com/photo-1534787238916-9ba6764efd4f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1331&q=80">
    </div>
  </div>

app/views/reviews/_form.html.erb
<section class="text-gray-600 body-font relative">
  
  <div class="container px-5 py-24 mx-auto flex">
    <div class="border 1px bg-white rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0 relative z-10 shadow-md">

      
     
      <div class="relative mb-4">
        <div>
            <%= simple_form_for [@booking.bike, @booking, @review] do |f| %>
                <%= f.input :review %>
                <%= f.submit class:"text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg " %>

            <% end %>
        </div>
      
      
    </div>
   
  </div>
</section>

app/views/reviews/new.html.erb
<%= render 'form', booking: @booking, review: @review %>

app/views/shared/_footer.html.erb
<div class="bg-gray-100">
  <div class="items-center justify-center">
    <div class="w-100 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
      <a class="flex title-font font-medium items-center justify-center text-gray-900">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-bike" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2C3E50" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <circle cx="5" cy="18" r="3" />
            <circle cx="19" cy="18" r="3" />
            <polyline points="12 19 12 15 9 12 14 8 16 11 19 11" />
            <circle cx="17" cy="5" r="1" />
          </svg>

        <span class="ml-1 mt-3 text-xl">We Wheel Bikes</span>
      </a>
        <p class="text-xs text-gray-500"> Ride the world the way you like </p>
    </div>

    <div class="md:text-left text-center">
      <div class="">
        <nav class="list-none">
            <%# <a class="text-gray-600 hover:text-gray-800 text-sm">Manage Your Content and Devices</a> %>
        </nav>
      </div>


      <span class="inline-flex sm:ml-auto sm:mt-0 justify-center sm:justify-start">
        <a class="text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>

      <div class="container mx-auto pb-3 px-5 flex flex-wrap flex-col sm:flex-row justify-content-center">
        <div class="">
          <a class="text-gray-600 px-2 hover:text-gray-800 text-sm">About us</a>
          <a class="text-gray-600 px-2 hover:text-gray-800 text-sm">|</a>
          <a class="text-gray-600 px-2 hover:text-gray-800 text-sm">T&C</a>
          <a class="text-gray-600 px-2 hover:text-gray-800 text-sm">|</a>
          <a class="text-gray-600 px-2 hover:text-gray-800 text-sm">Contact us</a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-white shadow-sm">
  <%= link_to root_path, class: "navbar-brand" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-bike" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2C3E50" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
      <circle cx="5" cy="18" r="3" />
      <circle cx="19" cy="18" r="3" />
      <polyline points="12 19 12 15 9 12 14 8 16 11 19 11" />
      <circle cx="17" cy="5" r="1" />
    </svg>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Host", new_bike_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="avatar dropdown-toggle h-10 w-10 rounded-full border-2 border-white shadow" style="background-image: url(https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YXZhdGFyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1100&q=60); background-size: cover;" id="navbarDropdown", data-toggle="dropdown" aria-haspopup= true aria-expanded= false>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Booking history", bookings_path, class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>